name: HamerReviews
favicon: null
layout_spectrum: 0.7065767
typography_spectrum: 0.3288364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.4747049
  saturation: 0.8600338
  rhythmicContrast: 0.4317032
purpose: []
