layout_spectrum: 0.7065767
typography_spectrum: 0.3288364
color:
  saturation: 0.8600338
  lightness: 0.4747049
  brandStrength: 0.4571489
  rhythmicContrast: 0.4317032
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: HamerReviews
