name: HamerReviews
favicon: null
layout_spectrum: 0.84901
typography_spectrum: 0.18279
title: Hamer Reviews
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21508233-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#8780aa'
    - '#ff8137'
    - '#73607e'
    - '#a2425e'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
